keepout_filter_mask_server:
  ros__parameters:
    topic_name: "keepout_filter_mask"
#    yaml_filename: "minicity.yaml" #idk fi i need this yet..

keepout_costmap_filter_info_server:
  ros__parameters:
    type: 0
    filter_info_topic: "keepout_costmap_filter_info"
    mask_topic: "keepout_filter_mask"
    base: 0.0
    multiplier: 1.0