amcl:
  ros__parameters:
    use_sim_time: false
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.2
    base_frame_id: "base_link"
    do_beamskip: false
    laser_max_range: -1.0
    laser_min_range: -1.0
    laser_model_type: "likelihood_field"
    recovery_alpha_fast: 0.1
    recovery_alpha_slow: 0.1
    resample_interval: 1
    robot_model_type: "nav2_amcl::DifferentialMotionModel"
    save_pose_rate: 0.5
    sigma_hit: 0.2
    tf_broadcast: true
    transform_tolerance: 1.0
    update_min_a: 0.2
    update_min_d: 0.25
    z_hit: 0.5
    z_max: 0.05
    z_rand: 0.5
    z_short: 0.05
    scan_topic: /scan
    qos_overrides:
      scan:
        subscription:
          reliability: best_effort
          history: keep_last
          depth: 10

amcl_map_client:
  ros__parameters:
    use_sim_time: false

amcl_rclcpp_node:
  ros__parameters:
    use_sim_time: false

controller_server_rclcpp_node:
  ros__parameters:
    use_sim_time: false

map_server:
  ros__parameters:
    yaml_filename: "/home/airou/PycharmProjects/arcpro_rl_base_case_waypointer/install/merger/share/merger/res/minicity.yaml"
    frame_id: "map"
    topic_name: "map"
    use_sim_time: false

controller_server:
  ros__parameters:
    use_stamped_cmd_vel: true
    cmd_vel_topic: "/cmd_vel"
    controller_plugins: [ "FollowPath" ]
    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
      goal_checker: "nav2_core::SimpleGoalChecker"
      progress_checker: "nav2_core::SimpleProgressChecker"

planner_server:
  ros__parameters:
    planner_plugins: [ 'GridBased' ]
    GridBased:
      plugin: 'nav2_smac_planner::SmacPlannerHybrid'
      minimum_turning_radius: 0.4
      motion_model_for_search: "REEDS_SHEPP"
      downsample_costmap: false

global_costmap:
  ros__parameters:
    filters: [ "keepout_filter" ]
    keepout_filter:
      plugin: "nav2_costmap_2d::KeepoutFilter"
      enabled: True
      filter_info_topic: "keepout_costmap_filter_info"
    footprint: "[ [0.12, 0.09], [0.12, -0.09], [-0.12, -0.09], [-0.12, 0.09] ]"
    use_sim_time: false
    global_frame: map
    robot_base_frame: "base_link"
    update_frequency: 1.0
    publish_frequency: 1.0
    transform_tolerance: 0.5
    plugins: [ "static_layer", "inflation_layer" ]
    static_layer:
      plugin: "nav2_costmap_2d::StaticLayer"
      map_subscribe_transient_local: True
    inflation_layer:
      plugin: "nav2_costmap_2d::InflationLayer"
      cost_scaling_factor: 3.0
      inflation_radius: 0.2
    always_send_full_costmap: True

local_costmap:
  ros__parameters:
    filters: [ "keepout_filter" ]
    keepout_filter:
      plugin: "nav2_costmap_2d::KeepoutFilter"
      enabled: True
      filter_info_topic: "keepout_costmap_filter_info"
    footprint: "[ [0.12, 0.09], [0.12, -0.09], [-0.12, -0.09], [-0.12, 0.09] ]"
    use_sim_time: false
    update_frequency: 5.0
    publish_frequency: 2.0
    global_frame: odom
    robot_base_frame: "base_link"
    rolling_window: true
    width: 3
    height: 3
    resolution: 0.05
    transform_tolerance: 0.5
    plugins: [ "obstacle_layer", "inflation_layer" ]
    obstacle_layer:
      plugin: "nav2_costmap_2d::ObstacleLayer"
      enabled: True
      observation_sources: scan
      scan:
        topic: /scan
        max_obstacle_height: 2.0
        min_obstacle_height: 0.0
        data_type: "LaserScan"
        marking: True
        clearing: True
    inflation_layer:
      plugin: "nav2_costmap_2d::InflationLayer"
      cost_scaling_factor: 3.0
      inflation_radius: 0.2
    always_send_full_costmap: True

bt_navigator:
  ros__parameters:
    use_sim_time: false
    global_frame: map
    robot_base_frame: base_link
    odom_topic: /odom
    bt_loop_duration: 10
    default_server_timeout: 20

keepout_filter_mask_server:
  ros__parameters:
    topic_name: "keepout_filter_mask"

keepout_costmap_filter_info_server:
  ros__parameters:
    type: 0
    filter_info_topic: "keepout_costmap_filter_info"
    mask_topic: "keepout_filter_mask"
    base: 0.0
    multiplier: 1.0

collision_monitor:
  ros__parameters:
    enabled: True
    base_frame_id: "base_link"
    odom_frame_id: "odom"
    observation_sources: ["scan"]
    scan:
      type: "scan"
      topic: "/scan"
    polygons: ["PolygonStop"]
    PolygonStop:
      type: "polygon"
      points: "[[0.4, 0.3], [0.4, -0.3], [0.05, -0.3], [0.05, 0.3]]"
      action_type: "slowdown"
      min_points: 4

docking_server:
  ros__parameters:
    use_sim_time: false
    dock_plugins: ["SimpleChargingDock"]
    SimpleChargingDock:
      plugin: "opennav_docking::SimpleChargingDock"
    docks:
      my_dummy_dock:
        type: "SimpleChargingDock"
        frame: "map"
        pose: [0.0, 0.0, 0.0]
        id: "dummy_dock_id"

opennav_docking_rclcpp_node:
  ros__parameters:
    use_sim_time: false

waypoint_follower:
  ros__parameters:
    loop_rate: 20
    stop_on_failure: false
    waypoint_task_executor_plugin: "wait_at_waypoint"
    introspection_mode: "disabled"
    wait_at_waypoint:
      plugin: "nav2_waypoint_follower::WaitAtWaypoint"
      enabled: True
      waypoint_pause_duration: 0
